name: ci
on:
  pull_request:
  push:

jobs:
  Test:
    name: ${{matrix.os}} ${{matrix.compiler}} ${{matrix.build_type}} ${{matrix.packaging_maintainer_mode == 'ON' && '(maintainer mode)' || ''}}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - os: ubuntu-latest
            compiler: llvm-21.1.8

          - os: ubuntu-latest
            compiler: gcc-14

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows' )}}

          cmake: 4.2.2
          ninja: true
          vcpkg: false
          ccache: false
          clangtidy: false


          cppcheck: false

          gcovr: false
          opencppcoverage: false

      - uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-lua
          path: |
            LuappDev/lua50
            LuappDev/lua51
            LuappDev/lua52
            LuappDev/lua53
            LuappDev/lua54
            LuappDev/lua55
            LuappDev/luajit

      - name: setup lua
        run:
          ./setup_lua.sh

      - name: Configure CMake
        run: |
          cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: |
          cmake --build ./build

      - name: Test
        working-directory: ./build
        run: |
          ctest --verbose
